### PR TITLE
Fixes #7

### LINKED ISSUE #7: Refactor Character.handleFollowing to use keys
Character.handleFollowing duplicates some of the movement logic necessary to correctly handle diagonal movement. Instead it should just create objects expressing the "keys" it would want to be pressing if it were a player and call Character.handleInputs with them.

### PR DESCRIPTION
**Pull request by Gankra**
handleFollowing now uses mock-key-input objects

### CODE REVIEW

**Comment by FinnStokes** [comment]
This looks good. I think that characters with different speeds might run into problems near corners but I don't think this changes that.

**Comment by Gankra** [comment]
Characters with different speeds would be a nightmare anyway. If the follower is too slow they'll straggle more and more, if the follower is too fast they'll likely stutter in and out of walking.

**Comment by FinnStokes** [comment]
Is there a reason we actually get them to walk rather than just jumping to the next followBuffer position?

**Comment by Gankra** [comment]
It's natural with respect to the animations being played, and also makes handling the "start" case fairly easy. I suppose it would be possible to just populate a series of fake point leading up to the character's initial position.

**Comment by FinnStokes** [comment]
Good points with the animations and initial movement. The reason I asked was because it would avoid any chance of the follower getting stuck. Either way, I have no problem with this being merged in.

**Comment by tinaun** [comment]
This looks good to me.

**Pull request merged**
